FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY ./go.mod ./
COPY ./go.sum ./

COPY ./surveyapi ./surveyapi
COPY ./siccore ./siccore

RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download

WORKDIR /app/surveyapi

RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -o main.sh


FROM alpine:latest

WORKDIR /app/surveyapi

RUN mkdir -p /app/surveyapi/logs /app/surveyapi/errors

COPY --from=builder /app/surveyapi/main.sh .
COPY ./surveyapi/.env .env

ENTRYPOINT ["./main.sh"]
