// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: siccore/sic.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_siccore_sic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_siccore_sic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_siccore_sic_proto_rawDescGZIP(), []int{0}
}

type ProxyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Code          int32                  `protobuf:"varint,4,opt,name=code,proto3" json:"code,omitempty"`
	Token         string                 `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyResponse) Reset() {
	*x = ProxyResponse{}
	mi := &file_siccore_sic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyResponse) ProtoMessage() {}

func (x *ProxyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_siccore_sic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyResponse.ProtoReflect.Descriptor instead.
func (*ProxyResponse) Descriptor() ([]byte, []int) {
	return file_siccore_sic_proto_rawDescGZIP(), []int{1}
}

func (x *ProxyResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ProxyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProxyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProxyResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ProxyResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ProxyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	IsSecure      bool                   `protobuf:"varint,4,opt,name=isSecure,proto3" json:"isSecure,omitempty"`
	Slug          []byte                 `protobuf:"bytes,5,opt,name=slug,proto3" json:"slug,omitempty"`
	Param         []byte                 `protobuf:"bytes,6,opt,name=param,proto3" json:"param,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyRequest) Reset() {
	*x = ProxyRequest{}
	mi := &file_siccore_sic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyRequest) ProtoMessage() {}

func (x *ProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_siccore_sic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyRequest.ProtoReflect.Descriptor instead.
func (*ProxyRequest) Descriptor() ([]byte, []int) {
	return file_siccore_sic_proto_rawDescGZIP(), []int{2}
}

func (x *ProxyRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ProxyRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ProxyRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ProxyRequest) GetIsSecure() bool {
	if x != nil {
		return x.IsSecure
	}
	return false
}

func (x *ProxyRequest) GetSlug() []byte {
	if x != nil {
		return x.Slug
	}
	return nil
}

func (x *ProxyRequest) GetParam() []byte {
	if x != nil {
		return x.Param
	}
	return nil
}

var File_siccore_sic_proto protoreflect.FileDescriptor

const file_siccore_sic_proto_rawDesc = "" +
	"\n" +
	"\x11siccore/sic.proto\x12\asiccore\"\a\n" +
	"\x05Empty\"\x81\x01\n" +
	"\rProxyResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x04 \x01(\x05R\x04code\x12\x14\n" +
	"\x05token\x18\x05 \x01(\tR\x05token\"\x94\x01\n" +
	"\fProxyRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x1a\n" +
	"\bisSecure\x18\x04 \x01(\bR\bisSecure\x12\x12\n" +
	"\x04slug\x18\x05 \x01(\fR\x04slug\x12\x14\n" +
	"\x05param\x18\x06 \x01(\fR\x05param2B\n" +
	"\x05Proxy\x129\n" +
	"\bSendData\x12\x15.siccore.ProxyRequest\x1a\x16.siccore.ProxyResponseB\x05Z\x03/pbb\x06proto3"

var (
	file_siccore_sic_proto_rawDescOnce sync.Once
	file_siccore_sic_proto_rawDescData []byte
)

func file_siccore_sic_proto_rawDescGZIP() []byte {
	file_siccore_sic_proto_rawDescOnce.Do(func() {
		file_siccore_sic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_siccore_sic_proto_rawDesc), len(file_siccore_sic_proto_rawDesc)))
	})
	return file_siccore_sic_proto_rawDescData
}

var file_siccore_sic_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_siccore_sic_proto_goTypes = []any{
	(*Empty)(nil),         // 0: siccore.Empty
	(*ProxyResponse)(nil), // 1: siccore.ProxyResponse
	(*ProxyRequest)(nil),  // 2: siccore.ProxyRequest
}
var file_siccore_sic_proto_depIdxs = []int32{
	2, // 0: siccore.Proxy.SendData:input_type -> siccore.ProxyRequest
	1, // 1: siccore.Proxy.SendData:output_type -> siccore.ProxyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_siccore_sic_proto_init() }
func file_siccore_sic_proto_init() {
	if File_siccore_sic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_siccore_sic_proto_rawDesc), len(file_siccore_sic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_siccore_sic_proto_goTypes,
		DependencyIndexes: file_siccore_sic_proto_depIdxs,
		MessageInfos:      file_siccore_sic_proto_msgTypes,
	}.Build()
	File_siccore_sic_proto = out.File
	file_siccore_sic_proto_goTypes = nil
	file_siccore_sic_proto_depIdxs = nil
}
