FROM python:3.12-slim

WORKDIR /app/pyreportapi

# System dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    make \
    libffi-dev \
    libssl-dev \
    pkg-config \
    libgdal-dev \
    gdal-bin \
    libgeos-dev \
    libproj-dev \
    proj-bin \
    libfreetype6-dev \
    libpng-dev \
    libcairo2 \
    libpango-1.0-0 \
    libpangoft2-1.0-0 \
    && rm -rf /var/lib/apt/lists/*

COPY ./pyreportapi/requirements.txt ./

RUN --mount=type=cache,target=/root/.cache/pip \
    pip install -r requirements.txt

COPY ./pyreportapi ./

COPY ./pyreportapi/.env.prod .env

CMD ["python", "main.py"]