# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sic.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'sic.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tsic.proto\x12\x07siccore\"\x07\n\x05\x45mpty\"\\\n\rProxyResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x0c\n\x04\x63ode\x18\x04 \x01(\x05\x12\r\n\x05token\x18\x05 \x01(\t\"i\n\x0cProxyRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x0e\n\x06method\x18\x03 \x01(\t\x12\x10\n\x08isSecure\x18\x04 \x01(\x08\x12\x0c\n\x04slug\x18\x05 \x01(\x0c\x12\r\n\x05param\x18\x06 \x01(\x0c\x32\x42\n\x05Proxy\x12\x39\n\x08SendData\x12\x15.siccore.ProxyRequest\x1a\x16.siccore.ProxyResponseB\x05Z\x03/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\003/pb'
  _globals['_EMPTY']._serialized_start=22
  _globals['_EMPTY']._serialized_end=29
  _globals['_PROXYRESPONSE']._serialized_start=31
  _globals['_PROXYRESPONSE']._serialized_end=123
  _globals['_PROXYREQUEST']._serialized_start=125
  _globals['_PROXYREQUEST']._serialized_end=230
  _globals['_PROXY']._serialized_start=232
  _globals['_PROXY']._serialized_end=298
# @@protoc_insertion_point(module_scope)
